[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = ["E", "F", "UP", "B", "SIM", "I", "ARG", "RUF"]
ignore = ["E501"]

[tool.mypy]
exclude = [".venv"]
disable_error_code = ["import-untyped", "assignment", "unused-ignore"]

follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
no_implicit_reexport = true
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = [".*"]
ignore_missing_imports = true
