[project]
name = "project-b"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = ["loguru~=0.6"]

[dependency-groups]
dev = ["mypy~=1.15.0", "tqdm~=4.67.1"]
lint = ["ruff~=0.9.5"]
