[project]
name = "project-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = ["loguru~=0.7.3"]

[dependency-groups]
dev = ["mypy~=1.15.0", "ipywidgets>=8.1.5"]
lint = ["ruff~=0.9.5"]
